import { supabase } from '../lib/supabase';
import { getActiveMembership } from './membershipService';
import type { Attendance, AttendanceCalendarData, AttendanceFilters, AttendanceStats, CheckInInput } from '../types';

export function localDateString(value = new Date()): string { const y = value.getFullYear(); const m = String(value.getMonth() + 1).padStart(2, '0'); const d = String(value.getDate()).padStart(2, '0'); return `${y}-${m}-${d}`; }
export function formatDurationMinutes(minutes: number): string { if (!Number.isFinite(minutes) || minutes <= 0) return '—'; const h = Math.floor(minutes / 60); const m = Math.round(minutes % 60); return h ? `${h}h ${m}m` : `${m}m`; }
export function durationMinutes(record: Pick<Attendance, 'check_in' | 'check_out'>): number { const end = record.check_out ? new Date(record.check_out).getTime() : Date.now(); return Math.max(0, (end - new Date(record.check_in).getTime()) / 60000); }
const select = '*, members(id, full_name, member_id, phone, profile_photo_url)';
const normalize = (row: Record<string, unknown>): Attendance => ({ id: String(row.id), member_id: String(row.member_id), check_in: String(row.check_in), check_out: (row.check_out as string | null) ?? null, date: String(row.date), status: row.status as Attendance['status'], notes: (row.notes as string | null) ?? null, created_at: String(row.created_at), updated_at: String(row.updated_at), member: (row.members as Attendance['member']) ?? undefined });

export async function getTodayAttendance(): Promise<Attendance[]> { const { data, error } = await supabase.from('attendance').select(select).eq('date', localDateString()).order('check_in', { ascending: false }); if (error) { console.error('[attendanceService.getTodayAttendance]', error); throw new Error('Unable to load attendance.'); } return ((data ?? []) as Record<string, unknown>[]).map(normalize); }
export async function getAttendance(filters: AttendanceFilters): Promise<{ data: Attendance[]; total: number }> { let query = supabase.from('attendance').select(select, { count: 'exact' }).eq('date', filters.date); if (filters.search.trim()) { const q = filters.search.trim(); query = query.or(`full_name.ilike.%${q}%,member_id.ilike.%${q}%,phone.ilike.%${q}%`, { foreignTable: 'members' }); } const from = (filters.page - 1) * filters.pageSize; const { data, count, error } = await query.order('check_in', { ascending: false }).range(from, from + filters.pageSize - 1); if (error) { console.error('[attendanceService.getAttendance]', error); throw new Error('Unable to load attendance.'); } return { data: ((data ?? []) as Record<string, unknown>[]).map(normalize), total: count ?? 0 }; }
export async function getAttendanceStats(date = localDateString()): Promise<AttendanceStats> { const { data, error } = await supabase.from('attendance').select('check_in, check_out, status').eq('date', date); if (error) { console.error('[attendanceService.getAttendanceStats]', error); throw new Error('Unable to load attendance statistics.'); } const rows = (data ?? []) as Pick<Attendance, 'check_in' | 'check_out' | 'status'>[]; const completed = rows.filter(r => r.check_out); const average = completed.length ? completed.reduce((sum, r) => sum + durationMinutes(r), 0) / completed.length : 0; return { todayCheckIns: rows.length, currentlyInside: rows.filter(r => !r.check_out).length, completedVisits: completed.length, averageVisitMinutes: average }; }
export async function checkInMember(input: CheckInInput): Promise<Attendance> { const membership = await getActiveMembership(input.member_id); if (!membership) throw new Error('Membership expired. Renew the membership before checking in.'); const { data: open, error: openError } = await supabase.from('attendance').select('id, check_in').eq('member_id', input.member_id).is('check_out', null).maybeSingle(); if (openError) { console.error('[attendanceService.checkInMember]', openError); throw new Error('Unable to verify current attendance.'); } if (open) throw new Error('Member is already checked in.'); const { data, error } = await supabase.from('attendance').insert({ member_id: input.member_id, notes: input.notes }).select(select).single(); if (error) { console.error('[attendanceService.checkInMember]', error); if (error.code === '23505') throw new Error('Member is already checked in.'); throw new Error('Unable to check in member.'); } return normalize(data as Record<string, unknown>); }
export async function checkOutMember(id: string): Promise<Attendance> { const { data, error } = await supabase.from('attendance').update({ check_out: new Date().toISOString(), status: 'completed' }).eq('id', id).is('check_out', null).select(select).single(); if (error) { console.error('[attendanceService.checkOutMember]', error); throw new Error('Unable to check out member.'); } return normalize(data as Record<string, unknown>); }
export async function getMemberAttendance(memberId: string): Promise<Attendance[]> { const { data, error } = await supabase.from('attendance').select(select).eq('member_id', memberId).order('check_in', { ascending: false }).limit(50); if (error) { console.error('[attendanceService.getMemberAttendance]', error); throw new Error('Unable to load attendance history.'); } return ((data ?? []) as Record<string, unknown>[]).map(normalize); }
export async function getAttendanceCalendar(fromDate: string, toDate: string): Promise<AttendanceCalendarData[]> { const { data, error } = await supabase.from('attendance').select('date').gte('date', fromDate).lte('date', toDate); if (error) { console.error('[attendanceService.getAttendanceCalendar]', error); throw new Error('Unable to load attendance calendar.'); } const counts: Record<string, number> = {}; for (const row of (data ?? []) as { date: string }[]) counts[row.date] = (counts[row.date] ?? 0) + 1; return Object.entries(counts).map(([date, count]) => ({ date, count })); }
export async function getWeeklyAttendance(): Promise<{ day: string; checkIns: number }[]> { const now = new Date(); const monday = new Date(now); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7)); const start = localDateString(monday); const endDate = new Date(monday); endDate.setDate(monday.getDate() + 6); const { data, error } = await supabase.from('attendance').select('date').gte('date', start).lte('date', localDateString(endDate)); if (error) { console.error('[attendanceService.getWeeklyAttendance]', error); throw new Error('Unable to load weekly attendance.'); } const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; const counts = labels.map(day => ({ day, checkIns: 0 })); for (const row of (data ?? []) as { date: string }[]) { const d = new Date(`${row.date}T00:00:00`); counts[(d.getDay() + 6) % 7].checkIns += 1; } return counts; }
export async function getPeakHours(): Promise<{ hour: number; checkIns: number }[]> { const d = new Date(); d.setDate(d.getDate() - 30); const { data, error } = await supabase.from('attendance').select('check_in').gte('check_in', d.toISOString()); if (error) { console.error('[attendanceService.getPeakHours]', error); throw new Error('Unable to load peak hours.'); } const counts: Record<number, number> = {}; for (const row of (data ?? []) as { check_in: string }[]) { const hour = new Date(row.check_in).getHours(); counts[hour] = (counts[hour] ?? 0) + 1; } return Object.entries(counts).map(([hour, checkIns]) => ({ hour: Number(hour), checkIns })).sort((a, b) => b.checkIns - a.checkIns); }
export async function exportAttendance(filters: AttendanceFilters): Promise<Attendance[]> { const result = await getAttendance({ ...filters, page: 1, pageSize: 10000 }); return result.data; }
