import { supabase } from '../lib/supabase';
import type { Expense, ExpenseFilters, ExpensePaymentMethod, ExpenseStatus } from '../types';

export const EXPENSE_CATEGORIES = ['Rent','Utilities','Equipment','Maintenance','Salaries','Marketing','Supplies','Cleaning','Software','Insurance','Other'];
export const EXPENSE_METHODS: { value: ExpensePaymentMethod; label: string }[] = [{ value: 'cash', label: 'Cash' }, { value: 'upi', label: 'UPI' }, { value: 'card', label: 'Card' }, { value: 'bank_transfer', label: 'Bank Transfer' }, { value: 'other', label: 'Other' }];
export async function getExpenses(filters: ExpenseFilters): Promise<Expense[]> { let q = supabase.from('expenses').select('*').order('expense_date', { ascending: false }).order('created_at', { ascending: false }); if (filters.search.trim()) { const term = filters.search.trim(); q = q.or(`title.ilike.%${term}%,vendor.ilike.%${term}%,expense_id.ilike.%${term}%`); } if (filters.category) q = q.eq('category', filters.category); if (filters.status) q = q.eq('status', filters.status); if (filters.method) q = q.eq('payment_method', filters.method); if (filters.fromDate) q = q.gte('expense_date', filters.fromDate); if (filters.toDate) q = q.lte('expense_date', filters.toDate); const { data, error } = await q; if (error) throw new Error(error.message); return (data ?? []) as Expense[]; }
export async function createExpense(input: Omit<Expense, 'id' | 'expense_id' | 'created_at' | 'updated_at'>): Promise<Expense> { const { data, error } = await supabase.from('expenses').insert(input).select().single(); if (error) throw new Error(error.message); return data as Expense; }
export async function updateExpense(id: string, input: Partial<Omit<Expense, 'id' | 'expense_id' | 'created_at' | 'updated_at'>>): Promise<Expense> { const { data, error } = await supabase.from('expenses').update(input).eq('id', id).select().single(); if (error) throw new Error(error.message); return data as Expense; }
export async function deleteExpense(id: string) { const { data: row } = await supabase.from('expenses').select('receipt_url').eq('id', id).maybeSingle(); if (row?.receipt_url) { const match = String(row.receipt_url).match(/expense-receipts\/(.+?)(?:\?|$)/); if (match) await supabase.storage.from('expense-receipts').remove([match[1]]); } const { error } = await supabase.from('expenses').delete().eq('id', id); if (error) throw new Error(error.message); }
export async function uploadExpenseReceipt(file: File): Promise<string> { const allowed = ['application/pdf','image/jpeg','image/png','image/webp']; if (!allowed.includes(file.type)) throw new Error('Receipt must be PDF, JPG, JPEG, PNG, or WEBP.'); if (file.size > 10 * 1024 * 1024) throw new Error('Receipt must be smaller than 10 MB.'); const ext = file.name.split('.').pop()?.toLowerCase() ?? 'bin'; const path = `receipts/${crypto.randomUUID()}.${ext}`; const { error } = await supabase.storage.from('expense-receipts').upload(path, file, { contentType: file.type, upsert: false }); if (error) throw new Error(error.message); const { data, error: urlError } = await supabase.storage.from('expense-receipts').createSignedUrl(path, 60 * 60 * 24 * 365); if (urlError || !data?.signedUrl) throw new Error(urlError?.message ?? 'Could not create secure receipt URL.'); return data.signedUrl; }
export function expenseSummary(rows: Expense[]) { const now = new Date(); const month = now.toISOString().slice(0, 7); const previous = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1)).toISOString().slice(0, 7); const paid = rows.filter(r => r.status === 'paid'); const thisMonth = paid.filter(r => r.expense_date.startsWith(month)).reduce((s,r) => s + Number(r.amount), 0); const lastMonth = paid.filter(r => r.expense_date.startsWith(previous)).reduce((s,r) => s + Number(r.amount), 0); const categories = new Map<string, number>(); rows.forEach(r => categories.set(r.category, (categories.get(r.category) ?? 0) + Number(r.amount))); const highest = [...categories.entries()].sort((a,b) => b[1]-a[1])[0]?.[0] ?? '—'; return { total: rows.reduce((s,r) => s + Number(r.amount), 0), thisMonth, lastMonth, pending: rows.filter(r => r.status === 'pending').reduce((s,r) => s + Number(r.amount), 0), highest, byCategory: [...categories].map(([name, value]) => ({ name, value })) }; }
