import { supabase } from '../lib/supabase';
import { createNotification } from './notificationService';
import type { ProgressPhoto, ProgressPhotoType, ProgressRecord } from '../types';

function reportProgressError(context: string, error: { message: string; code?: string; details?: string; hint?: string }): never {
  console.error(`[${context}]`, { message: error.message, code: error.code, details: error.details, hint: error.hint });
  throw new Error(error.message);
}

export async function getProgressRecords(memberId: string): Promise<ProgressRecord[]> { const { data, error } = await supabase.from('progress_records').select('*').eq('member_id', memberId).order('recorded_date', { ascending: true }).order('created_at', { ascending: true }); if (error) throw new Error(error.message); return (data ?? []) as ProgressRecord[]; }
export async function createProgressRecord(input: Omit<ProgressRecord, 'id' | 'created_at' | 'updated_at'>): Promise<ProgressRecord> { const { data, error } = await supabase.from('progress_records').insert(input).select().single(); if (error) reportProgressError('progress_records.insert', error); const record = data as ProgressRecord; void createNotification({ title: 'Progress Updated', message: `A new progress record${record.weight != null ? ` (${record.weight} kg)` : ''} was added.`, type: 'Progress', member_id: record.member_id, dedupe_key: `progress:${record.id}` }).catch(err => console.error('[progressService.notification]', err)); return record; }
export async function updateProgressRecord(id: string, input: Partial<Omit<ProgressRecord, 'id' | 'member_id' | 'created_at' | 'updated_at'>>): Promise<ProgressRecord> { const { data, error } = await supabase.from('progress_records').update(input).eq('id', id).select().single(); if (error) throw new Error(error.message); return data as ProgressRecord; }
export async function deleteProgressRecord(id: string) { const { error } = await supabase.from('progress_records').delete().eq('id', id); if (error) throw new Error(error.message); }
export async function getProgressPhotos(memberId: string): Promise<ProgressPhoto[]> { const { data, error } = await supabase.from('progress_photos').select('*').eq('member_id', memberId).order('taken_date', { ascending: false }); if (error) throw new Error(error.message); return (data ?? []) as ProgressPhoto[]; }
export async function uploadProgressPhoto(file: File, memberId: string, photoType: ProgressPhotoType, takenDate: string, notes = ''): Promise<ProgressPhoto> { if (!file.type.startsWith('image/')) throw new Error('Please select an image file.'); if (file.size > 5 * 1024 * 1024) throw new Error('Image must be smaller than 5 MB.'); const ext = file.name.split('.').pop()?.toLowerCase() ?? 'jpg'; const path = `members/${memberId}/${crypto.randomUUID()}.${ext}`; const { error: uploadError } = await supabase.storage.from('progress-photos').upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) throw new Error(uploadError.message); const { data: urlData, error: urlError } = await supabase.storage.from('progress-photos').createSignedUrl(path, 60 * 60 * 24 * 365); if (urlError || !urlData?.signedUrl) throw new Error(urlError?.message ?? 'Could not create secure photo URL.'); const { data, error } = await supabase.from('progress_photos').insert({ member_id: memberId, photo_url: urlData.signedUrl, photo_type: photoType, taken_date: takenDate, notes }).select().single(); if (error) throw new Error(error.message); return data as ProgressPhoto; }
export async function deleteProgressPhoto(photo: ProgressPhoto) { const match = photo.photo_url.match(/progress-photos\/(.+?)(?:\?|$)/); if (match) await supabase.storage.from('progress-photos').remove([match[1]]); const { error } = await supabase.from('progress_photos').delete().eq('id', photo.id); if (error) throw new Error(error.message); }
