import React, { useCallback, useEffect, useState } from 'react';
import { CreditCard, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { EmptyState } from '../components/ui/EmptyState';
import { ConfirmationDialog } from '../components/ui/ConfirmationDialog';
import { ToastContainer } from '../components/ui/Toast';
import { MembershipPlanCard } from '../components/memberships/MembershipPlanCard';
import { MembershipPlanForm } from '../components/memberships/MembershipPlanForm';
import { MembershipForm } from '../components/memberships/MembershipForm';
import { useToast } from '../hooks/useToast';
import type { Membership, MembershipPlan } from '../types';
import { cancelMembership, deleteMembershipPlan, getExpiredMemberships, getExpiringMemberships, getMembershipPlans, getMemberships, updateMembershipPlan } from '../services/membershipService';
import { formatDate } from '../utils/helpers';

type Tab = 'plans' | 'active' | 'expiring' | 'expired';

export function MembershipsPage() {
  const [tab, setTab] = useState<Tab>('plans'); const [plans, setPlans] = useState<MembershipPlan[]>([]); const [memberships, setMemberships] = useState<Membership[]>([]); const [loading, setLoading] = useState(true); const [planFormOpen, setPlanFormOpen] = useState(false); const [editingPlan, setEditingPlan] = useState<MembershipPlan | null>(null); const [deletePlan, setDeletePlan] = useState<MembershipPlan | null>(null); const [renewing, setRenewing] = useState<Membership | null>(null); const [error, setError] = useState(''); const { toasts, success, error: toastError, dismiss } = useToast();
  const loadPlans = useCallback(async () => { try { setPlans(await getMembershipPlans()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load membership plans.'); } }, []);
  const loadMemberships = useCallback(async () => { setLoading(true); try { setMemberships(tab === 'expiring' ? await getExpiringMemberships() : tab === 'expired' ? await getExpiredMemberships() : await getMemberships({ status: tab === 'active' ? 'active' : undefined })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load memberships.'); } finally { setLoading(false); } }, [tab]);
  useEffect(() => { loadPlans(); }, [loadPlans]); useEffect(() => { if (tab !== 'plans') loadMemberships(); }, [tab, loadMemberships]);
  function handlePlanSuccess(_plan: MembershipPlan) { setPlanFormOpen(false); setEditingPlan(null); loadPlans(); success(editingPlan ? 'Membership plan updated.' : 'Membership plan created.'); }
  async function togglePlan(plan: MembershipPlan) { try { await updateMembershipPlan({ id: plan.id, status: plan.status === 'active' ? 'inactive' : 'active' }); loadPlans(); success(plan.status === 'active' ? 'Plan deactivated.' : 'Plan activated.'); } catch (err) { toastError('Unable to update plan.', err instanceof Error ? err.message : undefined); } }
  async function removePlan() { if (!deletePlan) return; try { await deleteMembershipPlan(deletePlan.id); setDeletePlan(null); loadPlans(); success('Membership plan deleted.'); } catch (err) { setDeletePlan(null); toastError('Plan cannot be deleted.', err instanceof Error ? err.message : undefined); } }
  async function cancel(id: string) { try { await cancelMembership(id); await loadMemberships(); success('Membership cancelled.'); } catch (err) { toastError('Unable to cancel membership.', err instanceof Error ? err.message : undefined); } }
  const tabs: { id: Tab; label: string }[] = [{ id: 'plans', label: 'Plans' }, { id: 'active', label: 'Active Memberships' }, { id: 'expiring', label: 'Expiring Soon' }, { id: 'expired', label: 'Expired' }];
  async function retryLoad() { setError(''); if (tab === 'plans') await loadPlans(); else await loadMemberships(); }
  return <div className="p-4 sm:p-6 space-y-6 max-w-[1600px] mx-auto"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-den-text">Membership Plans</h1><p className="text-sm text-den-muted mt-1">Create and manage membership plans for TheFitnessDen.</p></div>{tab === 'plans' && <Button icon={<Plus size={15} />} onClick={() => { setEditingPlan(null); setPlanFormOpen(true); }}>Add Plan</Button>}</div><div className="flex gap-1 border-b border-den-border overflow-x-auto">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`px-4 py-3 text-sm whitespace-nowrap border-b-2 ${tab === item.id ? 'text-den-accent border-den-accent' : 'text-den-muted border-transparent hover:text-den-text'}`}>{item.label}</button>)}</div>{error && <div className="flex items-center justify-between rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3"><p className="text-sm text-red-300">{error}</p><Button variant="outline" size="sm" icon={<RefreshCw size={13} />} onClick={retryLoad}>Try Again</Button></div>}{tab === 'plans' ? <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{plans.length === 0 ? <div className="md:col-span-2 xl:col-span-3"><EmptyState icon={<CreditCard size={28} />} title="No membership plans yet" description="Create your first plan to start assigning memberships." action={{ label: 'Add Plan', onClick: () => setPlanFormOpen(true) }} /></div> : plans.map(plan => <MembershipPlanCard key={plan.id} plan={plan} onEdit={() => { setEditingPlan(plan); setPlanFormOpen(true); }} onToggle={() => togglePlan(plan)} onDelete={() => setDeletePlan(plan)} />)}</div> : <MembershipTable memberships={memberships} loading={loading} onRenew={setRenewing} onCancel={cancel} />}{renewing && <MembershipForm open member={renewing.member ?? { id: renewing.member_id, full_name: 'Member', member_id: renewing.member_id }} existing={renewing} mode="renew" onClose={() => setRenewing(null)} onSuccess={() => { setRenewing(null); loadMemberships(); success('Membership renewed.'); }} />}<MembershipPlanForm open={planFormOpen} plan={editingPlan} onClose={() => { setPlanFormOpen(false); setEditingPlan(null); }} onSuccess={handlePlanSuccess} /><ConfirmationDialog open={!!deletePlan} onClose={() => setDeletePlan(null)} onConfirm={removePlan} danger title="Delete membership plan?" description="This plan can only be deleted if it has never been assigned to a member." confirmLabel="Delete Plan" /><ToastContainer toasts={toasts} onDismiss={dismiss} /></div>;
}

function MembershipTable({ memberships, loading, onRenew, onCancel }: { memberships: Membership[]; loading: boolean; onRenew: (membership: Membership) => void; onCancel: (id: string) => void }) {
  if (loading) return <div className="rounded-xl border border-den-border bg-den-card p-6 text-sm text-den-muted">Loading memberships…</div>;
  if (!memberships.length) return <div className="rounded-xl border border-den-border bg-den-card"><EmptyState icon={<CreditCard size={28} />} title="All memberships are up to date" description="No memberships match this view." /></div>;
  return <div className="overflow-x-auto rounded-xl border border-den-border bg-den-card"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-den-border">{['Member', 'Plan', 'Start Date', 'End Date', 'Days Remaining', 'Price', 'Status', 'Actions'].map(h => <th key={h} className="text-left text-xs text-den-muted font-medium py-3 px-3 first:pl-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-den-border/60">{memberships.map(m => <tr key={m.id} className="hover:bg-white/[0.015]"><td className="py-3 px-3 first:pl-4"><p className="text-sm text-den-text">{m.member?.full_name ?? 'Member'}</p><p className="text-xs font-mono text-den-muted">{m.member?.member_id ?? m.member_id}</p></td><td className="py-3 px-3 text-den-text">{m.plan_name}</td><td className="py-3 px-3 text-den-muted">{formatDate(m.start_date)}</td><td className="py-3 px-3 text-den-muted">{formatDate(m.end_date)}</td><td className="py-3 px-3"><span className={m.days_remaining <= 7 && m.status === 'active' ? 'text-amber-400' : 'text-den-muted'}>{m.status === 'expired' ? 'Expired' : `${Math.max(0, m.days_remaining)} days`}</span></td><td className="py-3 px-3 text-den-text">₹{m.price.toLocaleString('en-IN')}</td><td className="py-3 px-3"><Badge variant={m.status === 'active' ? 'success' : m.status === 'expired' ? 'danger' : 'default'} size="sm" dot>{m.status}</Badge></td><td className="py-3 px-3"><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => onRenew(m)}>Renew</Button>{m.status === 'active' && <button onClick={() => onCancel(m.id)} className="p-2 text-red-400 hover:bg-red-500/10 rounded-lg" aria-label="Cancel membership"><Trash2 size={14} /></button>}</div></td></tr>)}</tbody></table></div>;
}
