import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, CalendarDays, Download, DollarSign, Dumbbell, Printer, RefreshCw, TrendingDown, TrendingUp, Users, Wallet } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button, Card, EmptyState, Select, SkeletonCard, Tabs } from '../components/ui';
import { useToast } from '../hooks/useToast';
import { csvDownload, getReportData, getReportRange, inRange, money, type ReportData, type ReportRange } from '../services/reportService';

type TabId = 'overview' | 'revenue' | 'members' | 'memberships' | 'attendance' | 'trainers' | 'workouts' | 'progress' | 'expenses';
const tabs = ['overview', 'revenue', 'members', 'memberships', 'attendance', 'trainers', 'workouts', 'progress', 'expenses'].map(id => ({ id, label: id === 'workouts' ? 'Workout Plans' : id[0].toUpperCase() + id.slice(1) }));
const colors = ['#a3e635', '#38bdf8', '#f59e0b', '#f472b6', '#a78bfa', '#2dd4bf', '#fb7185'];
const fmtDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
const sum = (rows: { amount: number }[]) => rows.reduce((total, row) => total + Number(row.amount || 0), 0);
function monthly(rows: { amount: number; date: string }[]) { const now = new Date(); const result: { key: string; month: string; amount: number }[] = []; for (let i = 5; i >= 0; i--) { const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - i, 1)); result.push({ key: d.toISOString().slice(0, 7), month: d.toLocaleString('en-US', { month: 'short' }), amount: 0 }); } rows.forEach(row => { const item = result.find(entry => entry.key === row.date.slice(0, 7)); if (item) item.amount += Number(row.amount || 0); }); return result; }

function Kpi({ label, value, icon: Icon, tone = 'accent', sub }: { label: string; value: string; icon: React.ElementType; tone?: string; sub?: string }) { return <Card className="min-h-[116px]"><div className="flex items-start justify-between"><p className="text-xs uppercase tracking-wider text-den-muted">{label}</p><span className={`rounded-xl p-2 bg-${tone}-500/10 text-${tone}-400`}><Icon size={17} /></span></div><p className="text-2xl font-bold text-den-text mt-4">{value}</p>{sub && <p className="text-xs text-den-muted mt-1">{sub}</p>}</Card>; }
function ChartCard({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <Card className="min-h-[300px]"><div className="mb-4"><h3 className="font-semibold text-den-text">{title}</h3>{description && <p className="text-xs text-den-muted mt-1">{description}</p>}</div>{children}</Card>; }
function ChartEmpty() { return <div className="h-56 flex items-center justify-center text-sm text-den-muted">No data for this period.</div>; }
function MoneyChart({ data, color }: { data: { month: string; amount: number }[]; color: string }) { return <ResponsiveContainer width="100%" height={220}><LineChart data={data}><CartesianGrid stroke="#2a2a38" strokeDasharray="3 3" /><XAxis dataKey="month" stroke="#71717a" fontSize={11} /><YAxis stroke="#71717a" fontSize={11} tickFormatter={v => `₹${Math.round(v / 1000)}k`} /><Tooltip contentStyle={{ background: '#111115', border: '1px solid #2a2a38', borderRadius: 8 }} formatter={(v) => money(Number(v))} /><Line type="monotone" dataKey="amount" stroke={color} strokeWidth={2.5} dot={{ r: 3, fill: color }} /></LineChart></ResponsiveContainer>; }
function CountChart({ data, color }: { data: { name: string; value: number }[]; color: string }) { return data.length ? <ResponsiveContainer width="100%" height={220}><BarChart data={data}><CartesianGrid stroke="#2a2a38" strokeDasharray="3 3" /><XAxis dataKey="name" stroke="#71717a" fontSize={11} /><YAxis allowDecimals={false} stroke="#71717a" fontSize={11} /><Tooltip contentStyle={{ background: '#111115', border: '1px solid #2a2a38', borderRadius: 8 }} /><Bar dataKey="value" fill={color} radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer> : <ChartEmpty />; }
function Donut({ data }: { data: { name: string; value: number }[] }) { return data.length ? <div className="flex flex-col sm:flex-row items-center gap-4"><ResponsiveContainer width="55%" height={220}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={55} outerRadius={82} paddingAngle={3}>{data.map((_, i) => <Cell key={i} fill={colors[i % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="space-y-2 text-xs">{data.map((item, i) => <div key={item.name} className="flex items-center gap-2"><span className="w-2 h-2 rounded-full" style={{ background: colors[i % colors.length] }} /><span className="text-den-muted capitalize">{item.name}</span><span className="text-den-text font-semibold">{item.value}</span></div>)}</div></div> : <ChartEmpty />; }
function Table({ title, headers, rows }: { title: string; headers: string[]; rows: (string | number)[][] }) { return <Card padding="none"><div className="px-5 py-4 border-b border-den-border"><h3 className="font-semibold text-den-text">{title}</h3></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-sm"><thead><tr className="text-xs text-den-muted border-b border-den-border">{headers.map(h => <th key={h} className="text-left px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-den-border/60">{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className="px-5 py-3 text-den-text">{cell}</td>)}</tr>)}</tbody></table></div> : <EmptyState title="No records in this range" description="Try a wider date range." />}</Card>; }

export function ReportsPage() {
  const { error } = useToast(); const [data, setData] = useState<ReportData | null>(null); const [loading, setLoading] = useState(true); const [active, setActive] = useState<TabId>('overview'); const [preset, setPreset] = useState('month'); const [customFrom, setCustomFrom] = useState(''); const [customTo, setCustomTo] = useState('');
  const range = useMemo(() => getReportRange(preset, customFrom, customTo), [preset, customFrom, customTo]);
  const load = async () => { setLoading(true); try { setData(await getReportData()); } catch (e) { error('Could not load reports', e instanceof Error ? e.message : 'Unable to read report data.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const metrics = useMemo(() => { if (!data) return { revenue: 0, expenses: 0, net: 0, activeMembers: 0, newMembers: 0, attendance: 0, activeTrainers: 0 }; const revenue = sum(data.payments.filter(p => p.status === 'paid' && inRange(p.payment_date, range))); const expenses = sum(data.expenses.filter(e => e.status !== 'cancelled' && inRange(e.expense_date, range))); return { revenue, expenses, net: revenue - expenses, activeMembers: data.members.filter(m => m.status === 'active').length, newMembers: data.members.filter(m => inRange(m.created_at.slice(0, 10), range)).length, attendance: data.attendance.filter(a => inRange(a.date, range)).length, activeTrainers: data.trainers.filter(t => t.status === 'active').length }; }, [data, range]);
  const exportCurrent = () => { if (!data) return; const members = new Map(data.members.map(m => [m.id, m])); if (active === 'expenses') csvDownload('thefitnessden-expenses.csv', ['Expense ID', 'Title', 'Category', 'Amount', 'Date', 'Vendor', 'Status'], data.expenses.filter(e => inRange(e.expense_date, range)).map(e => [e.expense_id, e.title, e.category, e.amount, e.expense_date, e.vendor, e.status])); else if (active === 'attendance') csvDownload('thefitnessden-attendance.csv', ['Member', 'Member ID', 'Check-in', 'Date', 'Status'], data.attendance.filter(a => inRange(a.date, range)).map(a => [members.get(a.member_id)?.full_name, members.get(a.member_id)?.member_id, a.check_in, a.date, a.status])); else if (active === 'members') csvDownload('thefitnessden-members.csv', ['Member ID', 'Name', 'Status', 'Joined Date'], data.members.filter(m => inRange(m.created_at.slice(0, 10), range)).map(m => [m.member_id, m.full_name, m.status, m.created_at.slice(0, 10)])); else csvDownload('thefitnessden-report.csv', ['Metric', 'Value'], [['Report', active], ['Range', range.label], ['Revenue', metrics.revenue], ['Expenses', metrics.expenses], ['Net Cash Flow', metrics.net]]); };
  if (loading) return <div className="p-4 sm:p-6 max-w-[1600px] mx-auto"><div className="h-10 w-72 shimmer rounded-lg mb-6" /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[1, 2, 3, 4].map(i => <SkeletonCard key={i} />)}</div></div>;
  if (!data) return <EmptyState icon={<BarChart3 size={24} />} title="Reports are unavailable" description="Check the Supabase tables and try again." action={{ label: 'Retry', onClick: () => void load() }} />;
  return <div className="reports-page p-4 sm:p-6 space-y-6 max-w-[1600px] mx-auto"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4 print:hidden"><div><p className="text-xs uppercase tracking-[0.2em] text-den-accent">Business intelligence</p><h1 className="text-2xl font-bold text-den-text mt-1">Reports &amp; Analytics</h1><p className="text-sm text-den-muted mt-1">Get actionable insights into your gym&apos;s performance.</p></div><div className="flex flex-wrap items-center gap-2"><Select value={preset} onChange={setPreset} options={[{ value: 'week', label: 'This Week' }, { value: 'month', label: 'This Month' }, { value: 'lastMonth', label: 'Last Month' }, { value: 'quarter', label: 'Last 3 Months' }, { value: 'year', label: 'This Year' }, { value: 'custom', label: 'Custom Range' }]} /><Button variant="outline" icon={<Download size={15} />} onClick={exportCurrent}>Export Report</Button><Button variant="outline" icon={<Printer size={15} />} onClick={() => window.print()}>Print Report</Button><Button variant="ghost" icon={<RefreshCw size={15} />} onClick={() => void load()} aria-label="Refresh reports" /></div></div>{preset === 'custom' && <div className="flex flex-wrap gap-2 print:hidden"><input type="date" value={customFrom} onChange={e => setCustomFrom(e.target.value)} className="h-10 bg-den-surface border border-den-border rounded-xl px-3 text-sm text-den-text" /><input type="date" value={customTo} onChange={e => setCustomTo(e.target.value)} className="h-10 bg-den-surface border border-den-border rounded-xl px-3 text-sm text-den-text" /></div>}<div className="hidden print:block"><h1 className="text-2xl font-bold text-black">TheFitnessDen — Reports &amp; Analytics</h1><p className="text-sm text-gray-600">Period: {range.label}</p></div><Tabs tabs={tabs} active={active} onChange={id => setActive(id as TabId)} className="print:hidden" /><ReportContent active={active} data={data} range={range} metrics={metrics} /></div>;
}

function ReportContent({ active, data, range, metrics }: { active: TabId; data: ReportData; range: ReportRange; metrics: { revenue: number; expenses: number; net: number; activeMembers: number; newMembers: number; attendance: number; activeTrainers: number } }) {
  const members = new Map(data.members.map(m => [m.id, m])); const planNames = new Map(data.plans.map(p => [p.id, p.name])); const workoutNames = new Map(data.workoutPlans.map(p => [p.id, p.name])); const revenueRows = data.payments.filter(p => p.status === 'paid' && inRange(p.payment_date, range)); const expenseRows = data.expenses.filter(e => e.status !== 'cancelled' && inRange(e.expense_date, range)); const attendanceRows = data.attendance.filter(a => inRange(a.date, range)); const revenueChart = monthly(data.payments.filter(p => p.status === 'paid').map(p => ({ amount: Number(p.amount), date: p.payment_date }))); const expenseChart = monthly(data.expenses.filter(e => e.status !== 'cancelled').map(e => ({ amount: Number(e.amount), date: e.expense_date })));
  const goals = Object.entries(data.members.reduce<Record<string, number>>((map, row) => { const key = row.fitness_goal?.replaceAll('_', ' ') ?? 'Unspecified'; map[key] = (map[key] ?? 0) + 1; return map; }, {})).map(([name, value]) => ({ name, value })); const growth = Object.entries(data.members.filter(m => inRange(m.created_at.slice(0, 10), range)).reduce<Record<string, number>>((map, row) => { const key = row.created_at.slice(0, 7); map[key] = (map[key] ?? 0) + 1; return map; }, {})).sort(([a], [b]) => a.localeCompare(b)).map(([name, value]) => ({ name, value })); const expensesByCategory = Object.entries(expenseRows.reduce<Record<string, number>>((map, row) => { map[row.category] = (map[row.category] ?? 0) + Number(row.amount); return map; }, {})).map(([name, value]) => ({ name, value })); const planDistribution = Object.entries(data.memberships.filter(m => m.status === 'active').reduce<Record<string, number>>((map, row) => { const key = planNames.get(row.plan_id) ?? 'Unknown'; map[key] = (map[key] ?? 0) + 1; return map; }, {})).map(([name, value]) => ({ name, value })); const attendanceTrend = Object.entries(attendanceRows.reduce<Record<string, number>>((map, row) => { map[row.date] = (map[row.date] ?? 0) + 1; return map; }, {})).sort(([a], [b]) => a.localeCompare(b)).map(([name, value]) => ({ name: name.slice(5), value })); const assignments = data.workoutAssignments.filter(a => a.status === 'active'); const assignedMemberIds = new Set(assignments.map(a => a.member_id));
  if (active === 'overview') return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Total Members" value={String(data.members.length)} icon={Users} /><Kpi label="Active Members" value={String(metrics.activeMembers)} icon={Users} tone="emerald" /><Kpi label="New Members" value={String(metrics.newMembers)} icon={TrendingUp} sub={range.label} /><Kpi label="Active Trainers" value={String(metrics.activeTrainers)} icon={Dumbbell} tone="sky" /><Kpi label="Membership Revenue" value={money(metrics.revenue)} icon={DollarSign} /><Kpi label="Expenses" value={money(metrics.expenses)} icon={Wallet} tone="amber" /><Kpi label="Net Cash Flow" value={money(metrics.net)} icon={metrics.net >= 0 ? TrendingUp : TrendingDown} tone={metrics.net >= 0 ? 'emerald' : 'red'} /><Kpi label="Attendance" value={String(metrics.attendance)} icon={Activity} tone="violet" sub={range.label} /></div><div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Monthly Revenue" description="Successful payments over the last six months"><MoneyChart data={revenueChart} color="#a3e635" /></ChartCard><ChartCard title="Monthly Expenses"><MoneyChart data={expenseChart} color="#f59e0b" /></ChartCard></div><div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Member Growth"><CountChart data={growth} color="#38bdf8" /></ChartCard><ChartCard title="Members by Goal"><Donut data={goals} /></ChartCard></div></>;
  if (active === 'revenue') return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Revenue in Range" value={money(sum(revenueRows))} icon={DollarSign} /><Kpi label="This Month" value={money(sum(data.payments.filter(p => p.status === 'paid' && p.payment_date.startsWith(new Date().toISOString().slice(0, 7)))))} icon={CalendarDays} /><Kpi label="Last Month" value={money(sum(data.payments.filter(p => p.status === 'paid' && p.payment_date.slice(0, 7) === new Date(Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth() - 1, 1)).toISOString().slice(0, 7))))} icon={TrendingUp} tone="sky" /><Kpi label="Average Monthly" value={money(sum(revenueRows) / Math.max(1, new Set(revenueRows.map(p => p.payment_date.slice(0, 7))).size))} icon={BarChart3} /></div><ChartCard title="Monthly Revenue"><MoneyChart data={revenueChart} color="#a3e635" /></ChartCard><Table title="Successful payments in range" headers={['Payment', 'Member', 'Amount', 'Date', 'Status']} rows={revenueRows.map(p => [p.transaction_id ?? p.id.slice(0, 8), members.get(p.member_id)?.full_name ?? 'Member', money(Number(p.amount)), fmtDate(p.payment_date), p.status])} /></>;
  if (active === 'expenses') return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Expenses in Range" value={money(sum(expenseRows))} icon={Wallet} tone="amber" /><Kpi label="This Month" value={money(sum(data.expenses.filter(e => e.status !== 'cancelled' && e.expense_date.startsWith(new Date().toISOString().slice(0, 7)))))} icon={CalendarDays} /><Kpi label="Last Month" value={money(sum(data.expenses.filter(e => e.status !== 'cancelled' && e.expense_date.slice(0, 7) === new Date(Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth() - 1, 1)).toISOString().slice(0, 7))))} icon={TrendingDown} /><Kpi label="Categories" value={String(expensesByCategory.length)} icon={BarChart3} /></div><div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Monthly Expenses"><MoneyChart data={expenseChart} color="#f59e0b" /></ChartCard><ChartCard title="Expenses by Category"><Donut data={expensesByCategory} /></ChartCard></div><Table title="Expenses in range" headers={['Expense', 'Category', 'Amount', 'Date', 'Status']} rows={expenseRows.map(e => [e.title, e.category, money(Number(e.amount)), fmtDate(e.expense_date), e.status])} /></>;
  if (active === 'members') return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Total Members" value={String(data.members.length)} icon={Users} /><Kpi label="Active Members" value={String(metrics.activeMembers)} icon={Users} tone="emerald" /><Kpi label="Inactive Members" value={String(data.members.filter(m => m.status !== 'active').length)} icon={TrendingDown} tone="amber" /><Kpi label="New in Range" value={String(metrics.newMembers)} icon={TrendingUp} sub={range.label} /></div><div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Member Growth"><CountChart data={growth} color="#38bdf8" /></ChartCard><ChartCard title="Members by Goal"><Donut data={goals} /></ChartCard></div></>;
  if (active === 'memberships') { const now = new Date().toISOString().slice(0, 10); return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Active Memberships" value={String(data.memberships.filter(m => m.status === 'active' && m.end_date >= now).length)} icon={Users} /><Kpi label="Expired" value={String(data.memberships.filter(m => m.status === 'expired' || m.end_date < now).length)} icon={TrendingDown} tone="amber" /><Kpi label="Expiring Soon" value={String(data.memberships.filter(m => m.status === 'active' && m.end_date >= now && m.end_date <= new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10)).length)} icon={CalendarDays} tone="sky" /><Kpi label="Membership Revenue" value={money(sum(data.memberships.map(m => ({ amount: Number(m.price) }))))} icon={DollarSign} /></div><ChartCard title="Membership Plan Distribution"><Donut data={planDistribution} /></ChartCard><Table title="Popular plans" headers={['Plan', 'Assigned Members']} rows={planDistribution.sort((a, b) => b.value - a.value).map(p => [p.name, p.value])} /></>; }
  if (active === 'attendance') return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Total Check-ins" value={String(data.attendance.length)} icon={Activity} /><Kpi label="Check-ins in Range" value={String(attendanceRows.length)} icon={CalendarDays} tone="sky" /><Kpi label="Today" value={String(data.attendance.filter(a => a.date === new Date().toISOString().slice(0, 10)).length)} icon={Activity} tone="emerald" /><Kpi label="Average Daily" value={(attendanceRows.length / Math.max(1, new Set(attendanceRows.map(a => a.date)).size)).toFixed(1)} icon={BarChart3} /></div><ChartCard title="Attendance Trend"><CountChart data={attendanceTrend} color="#38bdf8" /></ChartCard><Table title="Peak attendance days" headers={['Date', 'Check-ins']} rows={[...attendanceTrend].sort((a, b) => b.value - a.value).slice(0, 10).map(a => [a.name, a.value])} /></>;
  if (active === 'trainers') { const counts = data.members.reduce<Record<string, number>>((m, row) => { if (row.trainer_id) m[row.trainer_id] = (m[row.trainer_id] ?? 0) + 1; return m; }, {}); return <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi label="Total Trainers" value={String(data.trainers.length)} icon={Dumbbell} /><Kpi label="Active Trainers" value={String(metrics.activeTrainers)} icon={Dumbbell} tone="emerald" /><Kpi label="Assigned Members" value={String(Object.values(counts).reduce((a, b) => a + b, 0))} icon={Users} /><Kpi label="Unassigned Members" value={String(data.members.filter(m => !m.trainer_id).length)} icon={Users} tone="amber" /></div><Table title="Trainer performance" headers={['Trainer', 'Trainer ID', 'Assigned Members', 'Active Members', 'Attendance']} rows={data.trainers.map(t => { const assigned = data.members.filter(m => m.trainer_id === t.id); const visits = data.attendance.filter(a => assigned.some(m => m.id === a.member_id) && inRange(a.date, range)).length; return [t.full_name, t.trainer_id, assigned.length, assigned.filter(m => m.status === 'active').length, visits]; })} /></>; }
  if (active === 'workouts') return <><div className="grid grid-cols-2 lg:grid-cols-3 gap-4"><Kpi label="Active Workout Plans" value={String(data.workoutPlans.filter(p => p.status === 'active').length)} icon={Activity} /><Kpi label="Assigned Members" value={String(assignedMemberIds.size)} icon={Users} /><Kpi label="Without a Plan" value={String(data.members.length - assignedMemberIds.size)} icon={TrendingDown} tone="amber" /></div><ChartCard title="Workout Plan Distribution"><Donut data={Object.entries(assignments.reduce<Record<string, number>>((m, a) => { const key = workoutNames.get(a.workout_plan_id) ?? 'Unknown'; m[key] = (m[key] ?? 0) + 1; return m; }, {})).map(([name, value]) => ({ name, value }))} /></ChartCard></>;
  const recent = data.progress.filter(p => inRange(p.recorded_date, range)); const byMember = new Map<string, typeof data.progress>(); data.progress.forEach(p => byMember.set(p.member_id, [...(byMember.get(p.member_id) ?? []), p])); return <><div className="grid grid-cols-2 lg:grid-cols-3 gap-4"><Kpi label="Members With Recent Progress" value={String(new Set(recent.map(p => p.member_id)).size)} icon={TrendingUp} /><Kpi label="Updates in Range" value={String(recent.length)} icon={Activity} /><Kpi label="Members Tracked" value={String(byMember.size)} icon={Users} /></div><Table title="Progress summary" headers={['Member', 'Starting Weight', 'Current Weight', 'Change', 'Latest Body Fat']} rows={[...byMember.entries()].map(([id, records]) => { const sorted = [...records].sort((a, b) => a.recorded_date.localeCompare(b.recorded_date)); const weights = sorted.filter(r => r.weight != null); const first = weights[0]?.weight; const last = weights.at(-1)?.weight; const latest = sorted.at(-1); return [members.get(id)?.full_name ?? 'Member', first == null ? '—' : `${first} kg`, last == null ? '—' : `${last} kg`, first != null && last != null ? `${last - first > 0 ? '+' : ''}${last - first} kg` : '—', latest?.body_fat_percentage == null ? '—' : `${latest.body_fat_percentage}%`]; })} /></>;
}
