import React, { useEffect, useRef, useState } from 'react';
import { Bell, Building2, Database, KeyRound, Palette, Save, Settings as SettingsIcon, Trash2, Upload, UserRound, Zap } from 'lucide-react';
import { Button, Card, Input, Select } from '../components/ui';
import { useToast } from '../hooks/useToast';
import { useAuth } from '../hooks/useAuth';
import { useGymSettings } from '../context/GymSettingsContext';
import { defaultGymSettings, exportAllData, formatConfiguredCurrency, getNotificationPreferences, removeGymLogo, saveGymSettings, saveNotificationPreferences, uploadGymLogo, validateGymLogoFile, type GymSettings, type NotificationPreferences } from '../services/settingsService';
import { supabase } from '../lib/supabase';

type Section = 'profile' | 'account' | 'notifications' | 'appearance' | 'business' | 'data';
const nav = [{ id: 'profile', label: 'Gym Profile', icon: Building2 }, { id: 'account', label: 'Account', icon: UserRound }, { id: 'notifications', label: 'Notifications', icon: Bell }, { id: 'appearance', label: 'Appearance', icon: Palette }, { id: 'business', label: 'Business Settings', icon: SettingsIcon }, { id: 'data', label: 'Data Management', icon: Database }];

export function SettingsPage() {
  const { user, updatePassword } = useAuth(); const { settings, refreshSettings } = useGymSettings(); const { success, error } = useToast();
  const [section, setSection] = useState<Section>('profile'); const [gym, setGym] = useState<GymSettings>({ ...(defaultGymSettings as GymSettings), id: '', created_at: '', updated_at: '' }); const [prefs, setPrefs] = useState<NotificationPreferences | null>(null); const [saving, setSaving] = useState(false); const [file, setFile] = useState<File | null>(null); const [logoPreview, setLogoPreview] = useState<string | null>(null); const [logoBroken, setLogoBroken] = useState(false); const [password, setPassword] = useState(''); const [counts, setCounts] = useState<Record<string, number>>({}); const fileInputRef = useRef<HTMLInputElement>(null); const displayLogo = logoPreview || gym.logo_display_url || (gym.logo_url?.startsWith('http') ? gym.logo_url : null);
  useEffect(() => { if (settings) { setGym(settings); setLogoPreview(null); setLogoBroken(false); } }, [settings]); useEffect(() => () => { if (logoPreview) URL.revokeObjectURL(logoPreview); }, [logoPreview]); useEffect(() => { if (user) getNotificationPreferences(user.id).then(setPrefs).catch(e => error('Could not load notification preferences', e.message)); }, [user]); useEffect(() => { if (section === 'data') { Promise.all(['members', 'trainers', 'memberships', 'workout_plans'].map(async table => { const { count } = await supabase.from(table).select('id', { count: 'exact', head: true }); return [table, count ?? 0] as const; })).then(rows => setCounts(Object.fromEntries(rows))); } }, [section]);
  const update = (key: keyof GymSettings, value: string | number | null) => setGym(current => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { const logo = file ? await uploadGymLogo(file) : gym.logo_path ?? gym.logo_url; const next = await saveGymSettings({ ...gym, logo_url: logo, logo_path: logo }); localStorage.setItem('tfd-currency', next.currency); setGym(next); await refreshSettings(); setFile(null); setLogoPreview(null); success('Settings saved'); } catch (e) { error('Could not save settings', e instanceof Error ? e.message : ''); } finally { setSaving(false); } };
  const selectLogo = (nextFile: File | null) => { if (!nextFile) return; const message = validateGymLogoFile(nextFile); if (message) { error('Invalid logo', message); return; } if (logoPreview) URL.revokeObjectURL(logoPreview); setFile(nextFile); setLogoPreview(URL.createObjectURL(nextFile)); setLogoBroken(false); };
  const removeLogo = async () => { if (!gym.logo_url || !window.confirm('Remove the current gym logo?')) return; setSaving(true); try { const next = await removeGymLogo(gym.logo_url); setGym(next); await refreshSettings(); setFile(null); setLogoPreview(null); setLogoBroken(false); success('Logo removed'); } catch (e) { error('Could not remove logo', e instanceof Error ? e.message : ''); } finally { setSaving(false); } };
  const savePrefs = async () => { if (!user || !prefs) return; try { setSaving(true); setPrefs(await saveNotificationPreferences(user.id, prefs)); success('Notification preferences saved'); } catch (e) { error('Could not save preferences', e instanceof Error ? e.message : ''); } finally { setSaving(false); } };
  return <div className="p-4 sm:p-6 space-y-6 max-w-[1250px] mx-auto"><div><h1 className="text-2xl font-bold text-den-text">Settings</h1><p className="text-sm text-den-muted mt-1">Manage your gym information and application preferences.</p></div><div className="lg:hidden"><Select value={section} onChange={value => setSection(value as Section)} options={nav.map(item => ({ value: item.id, label: item.label }))} /></div><div className="grid lg:grid-cols-[230px_1fr] gap-6"><aside className="hidden lg:block space-y-1">{nav.map(item => <button key={item.id} onClick={() => setSection(item.id as Section)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm text-left transition-colors ${section === item.id ? 'bg-den-accent/10 text-den-accent' : 'text-den-muted hover:text-den-text hover:bg-white/5'}`}><item.icon size={17} />{item.label}</button>)}</aside><main className="space-y-5">
  {section === 'profile' && <Card><SectionTitle title="Gym Profile" description="This information is used throughout TheFitnessDen." /><div className="grid sm:grid-cols-2 gap-4"><Input label="Gym Name" value={gym.gym_name} onChange={e => update('gym_name', e.target.value)} /><Input label="Tagline" value={gym.tagline ?? ''} onChange={e => update('tagline', e.target.value)} /><Input label="Email" type="email" value={gym.email ?? ''} onChange={e => update('email', e.target.value)} /><Input label="Phone" value={gym.phone ?? ''} onChange={e => update('phone', e.target.value)} /><Input label="Address" value={gym.address ?? ''} onChange={e => update('address', e.target.value)} /><Input label="City" value={gym.city ?? ''} onChange={e => update('city', e.target.value)} /><Input label="State" value={gym.state ?? ''} onChange={e => update('state', e.target.value)} /><Input label="Country" value={gym.country ?? ''} onChange={e => update('country', e.target.value)} /><Input label="Postal Code" value={gym.postal_code ?? ''} onChange={e => update('postal_code', e.target.value)} /><Input label="Website" type="url" value={gym.website ?? ''} onChange={e => update('website', e.target.value)} /></div><div className="mt-5 p-4 rounded-xl border border-den-border bg-den-surface"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-den-text">Gym Logo</p><p className="text-xs text-den-muted mt-1">PNG, JPG, JPEG, or WEBP · maximum 5 MB</p></div><div className="flex gap-2"><Button size="sm" variant="outline" icon={<Upload size={14} />} onClick={() => fileInputRef.current?.click()}>Change Logo</Button>{gym.logo_url && <Button size="sm" variant="danger" icon={<Trash2 size={14} />} onClick={() => void removeLogo()}>Remove</Button>}</div></div><div className="mt-4 flex items-center gap-4"><div className="w-24 h-24 rounded-xl border border-den-border bg-den-card flex items-center justify-center overflow-hidden">{(displayLogo && !logoBroken) ? <img src={displayLogo} onError={() => setLogoBroken(true)} alt="Gym logo preview" className="w-full h-full object-contain" /> : <Zap size={28} className="text-den-accent" />}</div><div className="text-sm text-den-muted">{file ? <><span className="text-den-text">{file.name}</span><p className="text-xs mt-1">Save Changes to apply this logo.</p></> : gym.logo_url ? 'Current logo' : 'No logo uploaded'}</div></div><input ref={fileInputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { selectLogo(e.target.files?.[0] ?? null); e.currentTarget.value = ''; }} className="hidden" /></div><Actions saving={saving} onSave={() => void save()} /></Card>}
  {section === 'account' && <Card><SectionTitle title="Account" description="Manage your authenticated account securely." /><div className="space-y-4"><Info label="Email" value={user?.email ?? '—'} /><Info label="Account status" value={user ? 'Authenticated' : 'Signed out'} /><Info label="Last sign-in" value={user?.last_sign_in_at ? new Date(user.last_sign_in_at).toLocaleString() : '—'} /><div className="border-t border-den-border pt-5"><h3 className="font-semibold text-den-text mb-3">Change Password</h3><Input label="New password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 6 characters" /><Button className="mt-4" icon={<KeyRound size={15} />} onClick={async () => { if (password.length < 6) return error('Password is too short', 'Use at least 6 characters.'); try { await updatePassword(password); setPassword(''); success('Password updated'); } catch (e) { error('Could not update password', e instanceof Error ? e.message : ''); } }}>Change Password</Button></div></div></Card>}
  {section === 'notifications' && <Card><SectionTitle title="Notification Preferences" description="Choose which activity alerts you receive." />{prefs && <div className="space-y-2">{[['membership_expiry','Membership expiry reminders'],['payment_notifications','Payment notifications'],['new_member_notifications','New member notifications'],['workout_plan_notifications','Workout plan notifications'],['progress_notifications','Progress notifications'],['reminder_notifications','Reminder notifications']].map(([key, label]) => <label key={key} className="flex items-center justify-between gap-4 p-3 rounded-xl hover:bg-white/5 cursor-pointer"><span className="text-sm text-den-text">{label}</span><input type="checkbox" checked={Boolean(prefs[key as keyof NotificationPreferences])} onChange={e => setPrefs({ ...prefs, [key]: e.target.checked })} className="accent-lime-400 w-4 h-4" /></label>)}</div>}<Actions saving={saving} onSave={() => void savePrefs()} /></Card>}
  {section === 'appearance' && <Appearance onSaved={success} />}
  {section === 'business' && <Card><SectionTitle title="Business Settings" description="Configure defaults used by gym operations." /><div className="grid sm:grid-cols-2 gap-4"><Select label="Currency" value={gym.currency} onChange={value => update('currency', value)} options={['INR','USD','EUR','GBP'].map(value => ({ value, label: `${value} — ${formatConfiguredCurrency(100, value)}` }))} /><Input label="Timezone" value={gym.timezone} onChange={e => update('timezone', e.target.value)} /><Input label="Default Membership Duration (months)" type="number" min="1" value={gym.default_membership_duration} onChange={e => update('default_membership_duration', Number(e.target.value))} /><Select label="Default Payment Method" value={gym.default_payment_method} onChange={value => update('default_payment_method', value)} options={['cash','upi','card','bank_transfer'].map(value => ({ value, label: value.replace('_', ' ').toUpperCase() }))} /><Select label="Default Member Status" value={gym.default_member_status} onChange={value => update('default_member_status', value)} options={['active','inactive','suspended'].map(value => ({ value, label: value[0].toUpperCase() + value.slice(1) }))} /></div><Actions saving={saving} onSave={() => void save()} /></Card>}
  {section === 'data' && <DataManagement counts={counts} onExport={() => void exportAllData().then(() => success('Data exports downloaded')).catch(e => error('Export failed', e instanceof Error ? e.message : ''))} />}</main></div></div>;
}
function SectionTitle({ title, description }: { title: string; description: string }) { return <div className="mb-5"><h2 className="text-base font-semibold text-den-text">{title}</h2><p className="text-sm text-den-muted mt-1">{description}</p></div>; }
function Actions({ saving, onSave }: { saving: boolean; onSave: () => void }) { return <div className="flex justify-end mt-6 pt-4 border-t border-den-border"><Button loading={saving} icon={<Save size={15} />} onClick={onSave}>Save Changes</Button></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 p-3 rounded-xl bg-den-surface"><span className="text-sm text-den-muted">{label}</span><span className="text-sm text-den-text text-right">{value}</span></div>; }
function Appearance({ onSaved }: { onSaved: (title: string) => void }) { const [theme, setTheme] = useState(localStorage.getItem('tfd-theme') ?? 'dark'); const [accent, setAccent] = useState(localStorage.getItem('tfd-accent') ?? 'lime'); useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.dataset.accent = accent; }, [theme, accent]); const save = () => { localStorage.setItem('tfd-theme', theme); localStorage.setItem('tfd-accent', accent); onSaved('Appearance saved'); }; return <Card><SectionTitle title="Appearance" description="Keep the premium dark theme or choose a display preference." /><div className="grid sm:grid-cols-2 gap-4"><Select label="Theme" value={theme} onChange={setTheme} options={[{ value: 'dark', label: 'Dark' }, { value: 'light', label: 'Light' }, { value: 'system', label: 'System' }]} /><Select label="Accent" value={accent} onChange={setAccent} options={[{ value: 'lime', label: 'Lime' }, { value: 'blue', label: 'Blue' }, { value: 'purple', label: 'Purple' }, { value: 'orange', label: 'Orange' }]} /></div><Actions saving={false} onSave={save} /></Card>; }
function DataManagement({ counts, onExport }: { counts: Record<string, number>; onExport: () => void }) { return <Card><SectionTitle title="Data Management" description="Export operational data without authentication credentials or tokens." /><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['Members', 'members'], ['Trainers', 'trainers'], ['Memberships', 'memberships'], ['Workout Plans', 'workout_plans']].map(([label, key]) => <div key={key} className="p-3 rounded-xl bg-den-surface"><p className="text-xs text-den-muted">{label}</p><p className="text-xl font-bold text-den-text mt-2">{counts[key] ?? '—'}</p></div>)}</div><Button className="mt-5" variant="outline" icon={<Database size={15} />} onClick={onExport}>Export All Data</Button><div className="mt-6 border border-red-500/20 rounded-xl p-4"><p className="text-sm font-semibold text-red-400">Danger Zone</p><p className="text-xs text-den-muted mt-1">Only application preferences can be reset. Gym records are never deleted here.</p><Button variant="danger" size="sm" className="mt-3" onClick={() => { localStorage.removeItem('tfd-theme'); localStorage.removeItem('tfd-accent'); window.location.reload(); }}>Reset Application Preferences</Button></div></Card>; }
