import React, { useEffect, useState } from 'react';
import { Activity, UserPlus, UserMinus } from 'lucide-react';
import { Badge, Button, Modal } from '../ui';
import { useToast } from '../../hooks/useToast';
import { assignWorkoutPlan, getWorkoutPlans, removeWorkoutPlan } from '../../services/workoutService';
import type { Member, WorkoutPlan } from '../../types';

export function MemberWorkoutSection({ member }: { member: Member }) {
  const { success, error } = useToast(); const [plan, setPlan] = useState(member.current_workout_plan ?? null); const [plans, setPlans] = useState<WorkoutPlan[]>([]); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { setPlan(member.current_workout_plan ?? null); }, [member.id, member.current_workout_plan]);
  useEffect(() => { getWorkoutPlans({ search: '', status: 'active', goal: '', difficulty: '' }).then(setPlans).catch(() => setPlans([])); }, []);
  const assign = async (next: WorkoutPlan) => { setSaving(true); try { await assignWorkoutPlan(member.id, next.id, new Date().toISOString().slice(0, 10), null); setPlan({ id: next.id, plan_id: next.plan_id, name: next.name, goal: next.goal, difficulty: next.difficulty, duration_weeks: next.duration_weeks, start_date: new Date().toISOString().slice(0, 10), end_date: null, status: 'active' }); setOpen(false); success('Workout plan assigned'); } catch (e) { error('Could not assign workout plan', e instanceof Error ? e.message : ''); } finally { setSaving(false); } };
  const remove = async () => { if (!window.confirm('Remove this workout plan?')) return; try { await removeWorkoutPlan(member.id, plan?.id); setPlan(null); success('Workout plan removed'); } catch (e) { error('Could not remove workout plan', e instanceof Error ? e.message : ''); } };
  return <><section className="py-6 border-b border-den-border"><div className="flex items-center justify-between mb-4"><h3 className="text-xs font-semibold text-den-muted uppercase tracking-widest flex items-center gap-2"><Activity size={14} /> Workout Plan</h3>{plan ? <div className="flex gap-2"><Button size="sm" variant="outline" icon={<UserPlus size={13} />} onClick={() => setOpen(true)}>Change</Button><Button size="sm" variant="ghost" icon={<UserMinus size={13} />} onClick={remove}>Remove</Button></div> : <Button size="sm" icon={<UserPlus size={13} />} onClick={() => setOpen(true)}>Assign Plan</Button>}</div>{plan ? <div className="rounded-xl border border-den-accent/20 bg-den-accent/5 p-4"><div className="flex justify-between"><div><p className="font-semibold text-den-text">{plan.name}</p><p className="text-xs text-den-muted mt-1">{plan.plan_id} · {plan.goal || 'General Fitness'} · {plan.difficulty || 'Beginner'}</p></div><Badge variant="success">{plan.status}</Badge></div><p className="text-xs text-den-muted mt-3">Started {plan.start_date || '—'} · {plan.duration_weeks ?? '—'} weeks</p></div> : <p className="text-sm text-den-muted">No workout plan assigned</p>}</section><Modal open={open} onClose={() => setOpen(false)} title={plan ? 'Change Workout Plan' : 'Assign Workout Plan'}><div className="space-y-2">{plans.map(item => <button key={item.id} disabled={saving} onClick={() => assign(item)} className="w-full text-left rounded-xl border border-den-border p-3 hover:border-den-accent/50"><p className="text-sm text-den-text">{item.name}</p><p className="text-xs text-den-muted">{item.plan_id} · {item.goal || 'General Fitness'}</p></button>)}{!plans.length && <p className="text-sm text-den-muted text-center py-5">No active workout plans available.</p>}</div></Modal></>;
}
