import React, { useEffect, useMemo, useState } from 'react';
import { Drawer } from '../ui/Drawer';
import { Input } from '../ui/Input';
import { Select } from '../ui/Select';
import { Button } from '../ui/Button';
import type { Member, Membership, MembershipPlan } from '../../types';
import { calculateMembershipEndDate, createMembership, getMembershipPlans, renewMembership } from '../../services/membershipService';

interface Props { open: boolean; member: Pick<Member, 'id' | 'full_name' | 'member_id'> | null; existing?: Membership | null; mode?: 'assign' | 'renew'; onClose: () => void; onSuccess: (membership: Membership) => void; }

export function MembershipForm({ open, member, existing, mode = 'assign', onClose, onSuccess }: Props) {
  const [plans, setPlans] = useState<MembershipPlan[]>([]); const [planId, setPlanId] = useState(''); const [startDate, setStartDate] = useState(''); const [price, setPrice] = useState(''); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [loadingPlans, setLoadingPlans] = useState(false);
  useEffect(() => { if (!open) return; setError(''); setNotes(''); setStartDate(existing && mode === 'renew' ? existing.end_date : new Date().toISOString().slice(0, 10)); setPlanId(existing?.plan_id ?? ''); setPrice(existing ? String(existing.price) : ''); setLoadingPlans(true); getMembershipPlans(false).then(setPlans).catch(err => setError(err instanceof Error ? err.message : 'Unable to load plans.')).finally(() => setLoadingPlans(false)); }, [open, existing, mode]);
  const selected = plans.find(p => p.id === planId);
  const duration = selected?.duration_months ?? 0;
  const previewStart = mode === 'renew' && existing ? (() => { const d = new Date(`${existing.end_date}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + 1); return d.toISOString().slice(0, 10); })() : startDate;
  const endDate = selected && previewStart ? calculateMembershipEndDate(previewStart, duration) : '';
  const planOptions = useMemo(() => plans.map(p => ({ value: p.id, label: `${p.name} · ₹${p.price.toLocaleString('en-IN')} / ${p.duration_months} mo` })), [plans]);
  function handlePlanChange(value: string) { setPlanId(value); const plan = plans.find(p => p.id === value); if (plan) setPrice(String(plan.price)); }
  async function submit() { if (!member) return; if (!planId || !selected) return setError('Select a membership plan.'); const amount = Number(price); if (!Number.isFinite(amount) || amount < 0) return setError('Price must be zero or greater.'); setLoading(true); setError(''); try { const result = mode === 'renew' ? await renewMembership(member.id, planId, amount, notes.trim() || undefined) : await createMembership({ member_id: member.id, plan_id: planId, start_date: startDate, end_date: endDate, price: amount, notes: notes.trim() || undefined }); onSuccess(result); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save membership.'); } finally { setLoading(false); } }
  return <Drawer open={open} onClose={onClose} title={mode === 'renew' ? 'Renew Membership' : 'Assign Membership'} description={member ? `${member.full_name} · ${member.member_id}` : ''} width="md"><div className="space-y-4">{loadingPlans ? <p className="text-sm text-den-muted">Loading plans…</p> : <Select label="Membership Plan *" value={planId} onChange={handlePlanChange} options={[{ value: '', label: 'Select a plan' }, ...planOptions]} />}{mode === 'assign' ? <Input label="Start Date" type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /> : <div className="rounded-xl border border-den-border bg-den-surface p-3 text-sm text-den-muted">New membership starts on <span className="text-den-text">{previewStart}</span>, after the current membership ends.</div>}<div className="grid grid-cols-2 gap-3"><Input label="Duration" value={duration ? `${duration} ${duration === 1 ? 'month' : 'months'}` : '—'} readOnly /><Input label="Price (₹)" type="number" min="0" value={price} onChange={e => setPrice(e.target.value)} /></div><div className="rounded-xl bg-den-accent/5 border border-den-accent/20 p-3 text-sm text-den-muted">End date: <span className="text-den-accent font-medium">{endDate || 'Select a plan'}</span></div><div><label className="text-sm font-medium text-den-text">Notes</label><textarea value={notes} onChange={e => setNotes(e.target.value)} rows={3} className="mt-1.5 w-full bg-den-surface border border-den-border rounded-xl text-sm text-den-text px-3.5 py-2.5 resize-none" placeholder="Optional notes" /></div>{error && <p className="text-sm text-red-400">{error}</p>}</div><div className="flex justify-end gap-2 mt-6 pt-4 border-t border-den-border"><Button variant="outline" onClick={onClose} disabled={loading}>Cancel</Button><Button onClick={submit} loading={loading}>{mode === 'renew' ? 'Renew Membership' : 'Assign Membership'}</Button></div></Drawer>;
}
