-- TheFitnessDen — Workout Plans
create sequence if not exists public.workout_plan_id_seq;
create or replace function public.generate_workout_plan_id() returns text language plpgsql security definer set search_path = public as $$ begin return 'WP-' || lpad(nextval('public.workout_plan_id_seq')::text, 4, '0'); end; $$;
create table if not exists public.workout_plans (id uuid primary key default gen_random_uuid(), plan_id text unique not null default public.generate_workout_plan_id(), name text not null, description text, goal text, difficulty text, duration_weeks integer check (duration_weeks > 0), status text not null default 'active' check (status in ('active','inactive','draft')), created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workout_plan_members (id uuid primary key default gen_random_uuid(), workout_plan_id uuid not null references public.workout_plans(id) on delete cascade, member_id uuid not null references public.members(id) on delete cascade, start_date date, end_date date, status text not null default 'active' check (status in ('active','completed','cancelled')), created_at timestamptz not null default now(), unique (workout_plan_id, member_id));
create table if not exists public.workout_days (id uuid primary key default gen_random_uuid(), workout_plan_id uuid not null references public.workout_plans(id) on delete cascade, day_number integer not null check (day_number > 0), day_name text, focus text, created_at timestamptz not null default now(), unique (workout_plan_id, day_number));
create table if not exists public.exercises (id uuid primary key default gen_random_uuid(), name text unique not null, category text, muscle_group text, equipment text, description text, created_at timestamptz not null default now());
create table if not exists public.workout_day_exercises (id uuid primary key default gen_random_uuid(), workout_day_id uuid not null references public.workout_days(id) on delete cascade, exercise_id uuid not null references public.exercises(id) on delete cascade, sets integer, reps text, duration_minutes integer, rest_seconds integer, weight text, notes text, order_index integer not null default 0, created_at timestamptz not null default now(), unique (workout_day_id, exercise_id));
create index if not exists workout_plans_status_idx on public.workout_plans(status);
create index if not exists workout_plan_members_member_idx on public.workout_plan_members(member_id);
create index if not exists workout_days_plan_idx on public.workout_days(workout_plan_id);
create index if not exists workout_day_exercises_day_idx on public.workout_day_exercises(workout_day_id);
drop trigger if exists workout_plans_set_updated_at on public.workout_plans;
create trigger workout_plans_set_updated_at before update on public.workout_plans for each row execute function public.set_updated_at();
alter table public.workout_plans enable row level security;
alter table public.workout_plan_members enable row level security;
alter table public.workout_days enable row level security;
alter table public.exercises enable row level security;
alter table public.workout_day_exercises enable row level security;
drop policy if exists "Authenticated workout plan access" on public.workout_plans;
drop policy if exists "Authenticated workout plan member access" on public.workout_plan_members;
drop policy if exists "Authenticated workout day access" on public.workout_days;
drop policy if exists "Authenticated exercise access" on public.exercises;
drop policy if exists "Authenticated workout exercise access" on public.workout_day_exercises;
create policy "Authenticated workout plan access" on public.workout_plans for all to authenticated using (true) with check (true);
create policy "Authenticated workout plan member access" on public.workout_plan_members for all to authenticated using (true) with check (true);
create policy "Authenticated workout day access" on public.workout_days for all to authenticated using (true) with check (true);
create policy "Authenticated exercise access" on public.exercises for all to authenticated using (true) with check (true);
create policy "Authenticated workout exercise access" on public.workout_day_exercises for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.workout_plans, public.workout_plan_members, public.workout_days, public.exercises, public.workout_day_exercises to authenticated;
grant usage, select on sequence public.workout_plan_id_seq to authenticated;
insert into public.exercises (name, category, muscle_group, equipment) values ('Bench Press','Strength','Chest','Barbell'),('Push Ups','Strength','Chest','Bodyweight'),('Squat','Strength','Legs','Barbell'),('Leg Press','Strength','Legs','Machine'),('Lunges','Strength','Legs','Dumbbells'),('Deadlift','Strength','Back','Barbell'),('Lat Pulldown','Strength','Back','Cable'),('Pull Ups','Strength','Back','Bodyweight'),('Shoulder Press','Strength','Shoulders','Dumbbells'),('Bicep Curl','Strength','Biceps','Dumbbells'),('Tricep Pushdown','Strength','Triceps','Cable'),('Plank','Core','Abs','Bodyweight'),('Crunches','Core','Abs','Bodyweight') on conflict (name) do nothing;
notify pgrst, 'reload schema';
